### ISSUE TITLE
how do i add it to startup .. 

### ISSUE THREAD

**Issue by destx0** [nate-sys/hypr-empty#1]
exec-once = hypr-empty 
in hyprland.conf doesnot work ..but if i do hypr-empty in terminal starts it

**Comment by nthnd** [comment]
can you confirm that you can run other programs from your hyprland.conf ?

**Comment by Cornelius-Figgle** [comment]
I also have a similar issue, it doesn't auto-start when added to `Hyprland.conf`, however `waybar` and `hyprpaper` do. It works fine when ran from the terminal or from `rofi -show run`, but not `rofi -show drun` (this errors saying it can't find the file)

any ideas?

**Comment by nthnd** [comment]
If you have ~/.cargo/bin in your `PATH` I don't know why the programs aren't finding it. Maybe add `/home/<user>/.cargo/bin/hypr-empty` in Hyprland.conf instead of just hypr-empty?



> but not `rofi -show drun` (this errors saying it can't find the file)

Is the error from hypr-emty? if so can you send the backtrace?

**Comment by Cornelius-Figgle** [comment]
For some reason that solves it! I don't know if its because of how I edited `$PATH` (I just added an `EXPORT` line to the end of my `.bashrc`) or what but Hyprland seems to start `hypr-empty` fine with the full path

I think that it may be that Hyprland has its own copy of `$PATH` that it loads apps from (or it skips `.bashrc` initialisation?) and that doesn't have `/home/<user>/.cargo/bin` in its list

Anyways thank you for the solution :)
